version: "3.8"
services:
  backend-flask:
    image: python:3.10-slim-buster
    env_file:
      - .env
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    command: sh -c "cd /backend-flask && pip3 install -r requirements.txt && FLASK_DEBUG=1; python3 -m flask run --host=0.0.0.0 --port=4567"
  frontend-react-js:
    image: node:16.18
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
    command: sh -c "cd /frontend-react-js && npm install && npm start"
  db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  dynamodb-local:
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks:
  internal-network:
    driver: bridge
    name: cruddur

volumes:
  db:
    driver: local
